#!/bin/sh

# PROVIDE: nas_video
# REQUIRE: NETWORKING
# KEYWORD: shutdown

. /etc/rc.subr

name="nas_video"
rcvar="nas_video_enable"

load_rc_config "$name"

: "${nas_video_enable:=NO}"
: "${nas_video_user:=nasvideo}"
: "${nas_video_chdir:=/usr/local/mine_nas_ai_video}"
: "${nas_video_uv:=/usr/local/bin/uv}"
: "${nas_video_flags:=run nas-video}"

pidfile="/var/run/${name}.pid"
command="/usr/sbin/daemon"
command_args="-f -p ${pidfile} -u ${nas_video_user} /bin/sh -c 'cd ${nas_video_chdir} && exec ${nas_video_uv} ${nas_video_flags}'"

run_rc_command "$1"

